name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 如果有 nodejs 构建，如 Hexo/Hugo/Jekyll
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 安装依赖（如 package.json 存在）
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    # 构建静态文件（根据你的构建命令修改）
    - name: Build Site
      run: |
        if [ -f package.json ]; then
          npm run build
        fi

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # 根据你的构建输出目录调整
